language: python
python:
  - "3.5.2"

install: 
  - pip install -r requirements.txt
env:
  - APP_SETTINGS=testing

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres
  
script: 
  - nosetests --with-coverage --cover-package=v1

after_success:
  - coveralls

