language: python
python:
  - "3.5.2"
  

install: 
  - pip install -r requirements.txt

services:
    - postgresql
before_script:
    - psql -c 'create database flask_api;' -U postgres

script: 
  - nosetests --with-coverage

after_success:
  - coveralls