language: python
python:
  - "3.5.2"

install: 
  - pip install -r requirements.txt

services:
  - postgresq

before_script:
  - psql -c 'create database mydiary;' -U postgres

script: 
  - nosetests --with-coverage --cover-package=v1

after_success:
  - coveralls